### ISSUE TITLE
Undefined variable $ms

### ISSUE THREAD

**Issue by vvinci00** [concrete5-community/docker5#30]
requesting 9.0.1 version there's the same error on updating and connecting to concrete project:

in file `/app/concrete/src/Marketplace/Marketplace.php` line 88

Whoops \ Exception \ ErrorException (E_WARNING)
Undefined variable $ms

` 
        $this->isConnected = false;
 
        if ($csToken != '') {
            $fh = $this->app->make('helper/file');
            $installationService = $this->app->make(InstallationService::class);
            if ($installationService->isMultisiteEnabled()) {
                $ms = '&ms=1';
            }
            $csiURL = urlencode($this->getSiteURL());
            **$url = $this->config->get('concrete.urls.concrete') . $this->config->get('concrete.urls.paths.marketplace.connect_validate') . "?csToken={$csToken}&csiURL=" . $csiURL . "&csiVersion=" . APP_VERSION . $ms;**
            $vn = $this->app->make('helper/validation/numbers');
            $r = $this->get($url);
 
            if ($r === null && !$this->connectionError) {
                $this->isConnected = true;
            } else {
                if ($vn->integer($r)) {
                    $this->isConnected = false;
                    $this->connectionError = $r;
 `

no issue with upgrading from 8.5.4 > 9.1.3 
or with latest version

**Comment by mlocati** [comment]
Which PHP version are you using? Old ConcreteCMS v9 versions are not compatible with PHP 8.2 (you can set the PHP version with the `switch-php` CLI command, or with the `CCM_PHP_VERSION` environment variable).

Furthermore, this docker5 project is about having a handy docker image with Concrete: Concrete issues should be reported to https://github.com/concretecms/concretecms (but bugs for old Concrete versions shouldn't be reported anyway, since they may already have been fixed in more recent versions).
